### ISSUE TITLE
Crashes on server load

### ISSUE THREAD

**Issue by Aetheros** [daedalus4096/ThaumicWonders#3]
Description of the Issue:
The server crashes if the specified version is installed. Was fine before update

Version: 1.1.0

Stack Trace: https://pastebin.com/tgzcg0Wj

Steps to reproduce:

Put the new version on a server.

**Comment by daedalus4096** [comment]
This bug should be fixed in v1.1.1, which should be available on CurseForge later this evening.

**Comment by Aetheros** [comment]
[crash-2019-03-22_12.35.12-server.txt](https://github.com/daedalus4096/ThaumicWonders/files/2996295/crash-2019-03-22_12.35.12-server.txt)

Still crashing. Here is the full log.

**Comment by daedalus4096** [comment]
Strange.  I couldn't reproduce this after my initial fix.  I'll take another look.

**Comment by daedalus4096** [comment]
Okay, the fix should stick this time.  Please try again with v1.2.0.
